### ISSUE TITLE
Unusually long waiting time until the payment screen opens

### ISSUE THREAD

**Issue by Alcpaone** [pfpayments/jtl-5#7]
As soon as a customer has selected the payment option, it takes several seconds (unusually long time) until the selected payment mask opens and is ready for payment.

JTL Shop 5.2.4
PHP 8.1

**Comment by thibault-mambour** [comment]
Hi @Alcpaone , thank you for raising this. We will investigate this.
However, please note that it won't be the top priority as we want to first handle the other cases, sorry for the inconvenience.

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 

**PSP Shutdown in 3 days!** and we have to migrate our system to a new version before we can use your plugin. So please hurry up! Thank you

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee

**PSP Shutdown in 2 days!** No news?

**Comment by thibault-mambour** [comment]
hi @Alcpaone , on this specific case, there will not be any improvement done in the next couple of days, we are working on other areas first.

**Comment by Alcpaone** [comment]
@thibault-mambour @edgaraswallee we got Feedback from Customers that didn't order because we asked them (each one since 29.12.2023) why they didnt order -> most answer where "Payment page not loaded for too long".

In the checkout backend then it looks like this

<img width="377" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/48cd4532-ba48-489e-a97f-13da96b4b44b">

For the customers it looks like this. The yellow part is empty, nothing loading, nothing showing, that something is loading.
<img width="300" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/b211f918-debf-4520-8c05-0abee44621d3">

this is just until now this morning
<img width="275" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/3093e534-9842-4eff-af76-e0b4367244dd">

**Can you do a hotfix with a for example a gif thats shows something moving?**
![loading](https://github.com/pfpayments/jtl-5/assets/64169279/330a4422-e226-4f4e-be45-20d2ccb12bec)

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 
**Hi guys, please to something asap! this situation is unacceptable**  

Look at this from the checkout Backend and also again a customer message.

<img width="265" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/5c04bdcc-49fb-481e-9068-8e36fa7c3ce3">


<img width="345" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/ad0324d2-1ec0-4dfc-a2e1-69bbd9b9f73a">

**Comment by Alcpaone** [comment]
@thibault-mambour 
here maybe a other hint from a customer

<img width="193" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/06ca6d06-17cb-48cc-8357-68bb0aa4b329">

**Comment by Alcpaone** [comment]
@thibault-mambour
i think this shows also the journey of one more customer that we lost or what do you think about that?

<img width="238" alt="image" src="https://github.com/pfpayments/jtl-5/assets/64169279/6a12a442-d7cb-4fac-abef-7e7cc097997c">

**Comment by Alcpaone** [comment]
Hi guys, what ist the time table for the next release to fix this critical issue?

**Comment by thibault-mambour** [comment]
hi @Alcpaone it should be released by end of the day

**Comment by thibault-mambour** [comment]
hi @Alcpaone , we released a fix to have a loading screen. Could you please confirm if it works as expected ?

**Comment by Alcpaone** [comment]
@thibault-mambour first test looks good. will do more test later. thank you

**Comment by Alcpaone** [comment]
@thibault-mambour we had less customers with problems (they wait now because the see the gif) but is still slow! so we can still see customers leaving without paying because the postfinance checkout was way to slow (>5 seconds). We saw customers wait much longer but most don't like to wait more then 2 to 3 seconds. I accept that, because we are in 2023 and if you can't do it quick with a mobile phone,then it is a bad service. this is not my opinion, this is what customers expect.

So please rise the priority. Thank you

**Comment by Alcpaone** [comment]
@thibault-mambour @andrewrowanwallee @sauliususoniswallee @edgaraswallee 

**We can't wait any longer.** We have so many customers who drop out because of the long waiting time for the payment process. We have loyal customers who report this to us and we also get requests via chat asking why it takes minutes to pay. They see the gif but it just takes too long. We cannot accept this. 

**I would urge you to prioritize the task. It can't wait until next week.** Please provide feedback.

PS: again, could have been solved easily without stress last year. But now it's live and needs to be solved asap!

**Comment by thibault-mambour** [comment]
hi @Alcpaone , can you reach out to patricius for him to provide the shop details to us ?
Because when we check on local or with some other merchants shop, it looks ok (few seconds for the slowest).

**Comment by Alcpaone** [comment]
> hi @Alcpaone , can you reach out to patricius for him to provide the shop details to us ? Because when we check on local or with some other merchants shop, it looks ok (few seconds for the slowest).

ok

**Comment by Alcpaone** [comment]
> hi @Alcpaone , can you reach out to patricius for him to provide the shop details to us ? Because when we check on local or with some other merchants shop, it looks ok (few seconds for the slowest).

@thibault-mambour send yesterday asap Patricius informations as requestet. No anwer, no reaction until now.

We have measured TWINT payment transactions ourselves, for example, where the GIF is displayed for 60! seconds until the payment Form appears. (Mobile, no WLAN, different cities in Switzerland). Server has no load during this time. It must be something else!

**Comment by Alcpaone** [comment]
@thibault-mambour any news around this critical issue? We still see daily user not paying (timeout) and we lose orders and customers. Do you need anything? I would really be helpfull if you can delivery a update that finally solves this problems.

**Comment by Alcpaone** [comment]
@thibault-mambour i saw on the online shop gonser dot ch this picture before the paying starts:

looks like they found a way to show customer that they have to wait...

<img width="672" alt="2024-03-13 15_34_24-Kasse _ Online Shop Gonser - Sicher   Günstig einkaufen" src="https://github.com/pfpayments/jtl-5/assets/64169279/b31d7240-1c5a-47de-85e9-2f3685f1aa9b">

any news to this issue?
